apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-dp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "WITHDRAW_URL"
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: withdraw_url
            - name: "NOTIFICATION_URL"
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: notification_url
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP