apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}-svc
spec:
  selector:
    app: hw4app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      # smirnov_aa: this port is gateway port for outer clients
      port: 80
      # smirnov_aa: this port is inner container port, that application uses
      targetPort: 8000