openapi: 3.0.0
info:
  title: Billing Service API
  version: 1.0.0
paths:
  /api/billing/register:
    post:
      summary: Register a new account
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account registered successfully
  /api/billing/refill:
    post:
      summary: Refill account balance
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: amount
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Amount refilled successfully
  /api/billing/withdraw:
    post:
      summary: Withdraw money from account
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: amount
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Amount withdrawn successfully