# Default values for hw4.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  name: hw7order
  withdraw:
    #url: "http://hw7billing-service.hw7.cluster.local/hw7/api/billing/withdraw"
    url: "http://10.110.71.225/hw7/api/billing/withdraw"
  notification:
    #url: "http://hw7notification-service.hw7.cluster.local/hw7/api/notification"
    url: "http://10.105.94.150/hw7/api/notification"

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: hw7order
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  #tag: latest
  tag: 3

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80
  protocol: TCP
  targetPort: 8080