FROM bellsoft/liberica-openjdk-alpine-musl

# Set the working directory
WORKDIR /app

# Copy the JAR file
COPY target/Ex_User-1.0-SNAPSHOT.jar app.jar

# Expose the port
EXPOSE 8083

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]