@startuml
!include <C4/C4_Container>
!include <tupadr3/devicons2/chrome>
!include <tupadr3/devicons2/java>
!include <tupadr3/devicons2/javascript>

'LAYOUT_WITH_LEGEND()
'LAYOUT_LANDSCAPE()
'LAYOUT_LEFT_RIGHT()
'LAYOUT_TOP_DOWN()

!theme bluegray
skinparam backgroundColor white

HIDE_STEREOTYPE()

' If spaces are requested in the legend, legend text with space has to be defined (incl. all other additional details)
AddContainerTag("microService", $shape=EightSidedShape(), $legendText="micro service (eight sided) (no text, no back color)")

'skinparam linetype ortho
'skinparam linetype polyline

'skinparam defaultFontSize 25
'skinparam arrowFontSize 20

skinparam nodesep 50
skinparam ranksep 10

Person(person, "Пользователь")
Container(WEB_UI_INFO, "Веб-фронт инфопортала", "SPA:JavaScript", $tags="microService", $sprite="javascript")
Container(WEB_UI_LK, "Веб-фронт ЛК", "SPA:JavaScript", $tags="microService", $sprite="javascript")
Container(WEB_UI_MARKET, "Веб-фронт Маркет", "SPA:JavaScript", $tags="microService", $sprite="javascript")
Container(WEB_UI_SOCIAL, "Веб-фронт Соцсеть", "SPA:JavaScript", $tags="microService", $sprite="javascript")
Container(BFF, "BFF", "Container:SpringBoot", $tags="microService", $sprite="java")

Container(IDP, "Сервис IdP", "Container:SpringBoot", $tags="microService", $sprite="java")
Container(CALENDAR, "Календарь", "Container:SpringBoot", $tags="microService", $sprite="java")
Container(NOTIFICATION, "Уведомления", "Container:SpringBoot", $tags="microService", $sprite="java")
Container(INFOPORTAL, "Инфопортал", "Container:SpringBoot", $tags="microService", $sprite="java")

Boundary(LK, "Подсистема личного кабинета"){
    Container(API_Gateway_LK, "API-Gateway подсистемы ЛК", "Container:Kong")
    Container(CUSTOMER, "Пользователи", "Container:SpringBoot", $tags="microService", $sprite="java")
    Container(INVENTORY, "Инвентарь", "Container:SpringBoot", $tags="microService", $sprite="java")
    Container(ADVICE, "Рекомендации", "Container:SpringBoot", $tags="microService", $sprite="java")
}

Boundary(MARKET, "Подсистема Маркет"){
    Container(API_Gateway_Market, "API-Gateway подсистемы Маркет", "Container:Kong")
    Container(ORDER, "Заказ", "Container:SpringBoot", $tags="microService", $sprite="java")
    Container(CATALOGUE, "Каталог", "Container:SpringBoot", $tags="microService", $sprite="java")
    Container(WAREHOUSE, "Склад", "Container:SpringBoot", $tags="microService", $sprite="java")
    Container(BASKET, "Корзина", "Container:SpringBoot", $tags="microService", $sprite="java")
    Container(DELIVERY, "Доставка", "Container:SpringBoot", $tags="microService", $sprite="java")
    Container(INVOICE, "Платеж", "Container:SpringBoot", $tags="microService", $sprite="java")
    System(ERP, "ERP-система")
    System(BUH, "Бухгалтерская система")
}

Boundary(SOCIAL, "Подсистема Соцсети"){
    Container(GROUP_ACTIVITY, "Групповые мероприятия", "Container:SpringBoot", $tags="microService", $sprite="java")
}

Rel(person, WEB_UI_INFO, "Использует", style)
Rel(person, WEB_UI_LK, "Использует")
Rel(person, WEB_UI_MARKET, "Использует")
Rel(person, WEB_UI_SOCIAL, "Использует")

Rel(WEB_UI_INFO, BFF, "Вызывает", "HTTP/REST")
Rel(WEB_UI_LK, BFF, "Вызывает", "HTTP/REST")
Rel(WEB_UI_MARKET, BFF, "Вызывает", "HTTP/REST")
Rel(WEB_UI_SOCIAL, BFF, "Вызывает", "HTTP/REST")

Rel(BFF, IDP, "Вызывает", "HTTP/REST")

Rel(BFF, API_Gateway_LK, "Вызывает", "HTTP/REST")
Rel(BFF, API_Gateway_Market, "Вызывает", "HTTP/REST")

Rel(API_Gateway_LK, INVENTORY, "Вызывает", "HTTP/REST")
Rel(API_Gateway_LK, CUSTOMER, "Вызывает", "HTTP/REST")
Rel(API_Gateway_LK, ADVICE, "Вызывает", "HTTP/REST")

Rel(API_Gateway_Market, CATALOGUE, "Вызывает", "HTTP/REST")
Rel(API_Gateway_Market, BASKET, "Вызывает", "HTTP/REST")
Rel(API_Gateway_Market, ORDER, "Вызывает", "HTTP/REST")

Rel(BFF, CALENDAR, "Вызывает", "HTTP/REST")
Rel(BFF, INFOPORTAL, "Вызывает", "HTTP/REST")

Rel(BASKET, ORDER, "Вызывает", "HTTP/REST")

Rel(CATALOGUE, BASKET, "Вызывает", "HTTP/REST")

Rel(ORDER, INVOICE, "Отправляет команду", "JMS/AMQP")
Rel(ORDER, DELIVERY, "Вызывает", "HTTP/REST")
Rel(ORDER, NOTIFICATION, "Отправляет команду", "JMS/AMQP")
Rel(ORDER, WAREHOUSE, "Вызывает API бронирования и реализации товаров", "HTTP/REST")

Rel(ERP, WAREHOUSE, "Запрос складских остатков", "HTTP/REST")
Rel(BUH, INVOICE, "Импорт платежей", "JMS/AMQP")

Rel(CUSTOMER, NOTIFICATION, "Отправляет команду", "JMS/AMQP")
Rel(DELIVERY, NOTIFICATION, "Отправляет команду", "JMS/AMQP")

Rel(WAREHOUSE, CATALOGUE, "Отправляет позиции на складе", "JMS/AMQP")
Rel(GROUP_ACTIVITY, CALENDAR, "Отправляет событие", "JMS/AMQP")

Rel(INVENTORY, ADVICE, "Отправляет команду на генерацию рекомендаций", "JMS/AMQP")
Rel(ADVICE, CUSTOMER, "Запрашивает профиль пользователя", "HTTP/REST")
Rel(ADVICE, API_Gateway_Market, "Запрашивает продукты", "HTTP/REST")
Rel(ADVICE, INVENTORY, "Отправляет рекомендацию", "JMS/AMQP")


SHOW_LEGEND()
@enduml